name: Sync commits with azure devops
on:
  workflow_dispatch:
  schedule:
  - cron: "31 0 * * *"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'runner'
    - uses: actions/checkout@v2
      with:
        repository: ${{secrets.TRACKER_REPO}}
        token: ${{secrets.GH_WRITE_TOKEN}}
        path: 'tracker'
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Update git configs
      run: git config --global user.email "${{secrets.USER_EMAIL}}" && git config --global user.name "${{secrets.USER_NAME}}"
    - name: Force tracker onto master
      working-directory: ./tracker
      run: |
        git branch -M master
        git status
        git branch -a
    - name: Install node dependencies
      run: npm i
      working-directory: ./runner
    - name: Sync with azure
      run: npm run start
      working-directory: ./runner
      env:
        PAT: ${{secrets.PAT}}
        ORG: ${{secrets.ORG}}
        DAYS_LOOKUP: ${{secrets.DAYS_LOOKUP}}
        COMMITS_FOLDER_PATH: ../tracker
        AZURE_NAME: ${{secrets.AZURE_NAME}}
